### DISCUSSION TITLE
About the bug of tool properties-to-yaml

### DISCUSSION THREAD

**Discussion by lzb-libra** [he3-app/he3-feedback#322] [Bug Report]
我又这一段 properties 配置信息

```
spring.datasource.druid.username=test
spring.datasource.druid.password=123
spring.datasource.druid.url=jdbc:mysql://localhost:3306/www?useUnicode=true&useOldAliasMetadataBehavior=true&autoReconnect=true
```

使用工具转换后变成了这样子
```
spring:
  datasource:
    druid:
      username: test
      password: "123"
      url: jdbc:mysql://localhost:3306/www?useUnicode
```
不仅将我的123数字变成了字符串，而且还丢失了部分内容
