### DISCUSSION TITLE
About the bug of tool yaml-to-json

### DISCUSSION THREAD

**Discussion by fatflowers** [he3-app/he3-feedback#402] [Bug Report]
### Version
yaml-to-json 1.0.3

### Environment
Mac v2.0.20

### Steps to reproduce

```
items:
  - &membership-start
    id: membership-start
    tier: 1
  - <<: *membership-start
    id: membership-plus

```

### What is expected?

```
{
  "items": [
    {
      "id": "membership-start",
      "tier": 1
    },
    {
      "id": "membership-plus",
      "tier": 1
    }
  ]
}
```
### What is actually happening?
```
{
  "items": [
    {
      "id": "membership-start",
      "tier": 1
    },
    {
      "<<": {
        "id": "membership-start",
        "tier": 1
      },
      "id": "membership-plus"
    }
  ]
}
```
